"""Format script for BGP Malformed Packet test cases.

Reads raw outputs generated by CrossHair, canonicalizes and dedupes them,
evaluates using the executable model, and writes bgp_test_suite_formatted.json.
"""

import argparse
import json
import os
import sys
from typing import Iterator

# Bootstrap path
_HERE = os.path.dirname(os.path.abspath(__file__))      # examples/bgp_malformed_packets/
_EXAMPLES = os.path.dirname(_HERE)                       # examples/
sys.path.insert(0, os.path.join(_EXAMPLES, "lib"))
sys.path.insert(0, _EXAMPLES)

from bgp_malformed_packets.api_bgp_malformed import BGPState, BState, BEvent, RFCStandard

DEFAULT_INPUT = os.path.join(_HERE, "tests", "bgp_argdict.txt")
DEFAULT_OUTPUT = os.path.join(_HERE, "tests", "bgp_test_suite_formatted.json")

STATE_NAMES = {0: "IDLE", 1: "CONNECT", 2: "OPENSENT", 3: "ESTABLISHED"}
EVENT_NAMES = {
    10: "TCP_CONN_START", 
    11: "RCV_OPEN", 
    12: "RCV_VALID_UPDATE",
    13: "RCV_KEEPALIVE",
    14: "RCV_UPDATE_MISSING_MANDATORY",
    15: "RCV_UPDATE_BAD_FLAGS",
    16: "RCV_UPDATE_BAD_LENGTH"
}

def read_argdict(path: str) -> Iterator[dict]:
    if not os.path.exists(path):
        return
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            yield eval(line, {"__builtins__": {}}, {})

def evaluate(events: list[int], rfc_val: int) -> list[dict]:
    rfc = RFCStandard(rfc_val)
    state = BGPState(BState.IDLE)
    sequence = []
    
    for idx, e_val in enumerate(events):
        event = BEvent(e_val)
        prev_state = state.fsm_state
        next_state, action = state.transition(event, rfc)
        
        sequence.append({
            "step": idx,
            "expected_state": STATE_NAMES[int(prev_state)],
            "action_event": EVENT_NAMES[e_val],
            "resulting_state": STATE_NAMES[int(next_state)],
            "action_taken": action
        })
        state.fsm_state = next_state
        
    return sequence

def main():
    parser = argparse.ArgumentParser(description="Format raw BGP CrossHair test outputs.")
    parser.add_argument("input", nargs="?", default=DEFAULT_INPUT)
    parser.add_argument("-o", "--output", default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    
    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    
    seen = set()
    test_cases = []
    counter = 0
    
    for raw_case in read_argdict(args.input):
        events = raw_case.get("events", [])
        rfc_val = raw_case.get("rfc_standard_val", 7606)
        
        # Filter out empty, out-of-bounds, or invalid event sequences
        if len(events) < 1 or len(events) > 7 or rfc_val not in (4271, 7606):
            continue
        if any(e not in EVENT_NAMES for e in events):
            continue
            
        # Deduplication key
        key = (tuple(events), rfc_val)
        if key in seen:
            continue
        seen.add(key)
        
        sequence = evaluate(events, rfc_val)
        
        # Only include test cases that successfully progress or check malformed behavior
        counter += 1
        test_cases.append({
            "test_id": counter,
            "rfc_standard": str(rfc_val),
            "sequence": sequence
        })
        
    with open(args.output, "w") as f:
        json.dump(test_cases, f, indent=2)
        
    print(f"Read path:      {args.input}")
    print(f"Deduplicated:   {len(test_cases)} test cases")
    print(f"Formatted JSON: {args.output}")

if __name__ == "__main__":
    main()
